language: go 
go: 
  - 1.18.0

sudo: required 

os:       
  - linux

notifications:  
  email: lovelacelee@gmail.com

go_import_path: 
  - github.com/pkg/errors

before_install: 
  - go mod tidy

install: true 

script: 
  - echo "run"
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go test -v ./...

after_success: 
  - bash <(curl -s https://codecov.io/bash)