project:
  name: clsgo
  version: v1

database:
  default:
    dsn: "lee:lovelace@tcp(192.168.137.100:3306)/test?charset=utf8&parseTime=True&loc=Local"
    type: "mysql"
    cache: "redis.default"
  test:
    dsn: "lee:lovelace@tcp(192.168.137.100:3306)/test"
    type: "mysql"
  sqlite:
    dsn: "file::memory:?cache=shared"
    # dsn : "clsgo.db"
    type: "sqlite"
server:
  openapiPath: "/api.json"
  swaggerPath: "/api"

rabbitmq:
  server: amqp://test:test@192.168.137.100:5672/
  reconnect: 3 # Seconds When reconnecting to the server after connection failure
  reinit: 1 # Seconds When setting up the channel after a channel exception
  resend: 1 # Seconds When resending messages the server didn't confirm
# Sync with GF
redis.cache:
  address: 192.168.3.207:6379
  db: 15
  pass: lovelacelee
  idleTimeout: 600
redis.default:
  Address: 192.168.137.100:6379
  Db: 15
  pass: lovelacelee
  idleTimeout: 600
# Sync with GF
# See more: https://pkg.go.dev/github.com/gogf/gf/v2/os/glog#Config
logger:
  # configuration item names are not case sensitive
  # Log file path. The default value is null,
  # indicating that the device is disabled and output to the terminal only.
  path: "logs/"
  # Log file format. The default is"{Y-m-d}.log"
  file: "{Y-m-d}.log"
  # Error stack
  stStatus: 0
  # Log output Level [dev/prod/none/debu/info/noti/warn/erro/crit/pani/fata]
  level: "all"
  # Scrolling split files by log file size. The default value is 0,
  # which indicates that the rolling shard feature is disabled
  rotateSize: "5MB"
  # Clears shard files based on the number of files shard.
  # This is valid when the scrolling shard feature is enabled.
  # The default value is 0, indicating that no backup is performed
  rotateBackupLimit: 1
  # Generally, you do not need to set the time detection interval for rolling segmentation.
  # The default value is 1 hour
  rotateCheckInterval: "1m"
  RotateBackupExpire: "1d"
  clsgo:
    stStatus: 0
    prefix: "[CLSGO]"
    level: "dev"
