project:
  name: clsgo
# sync with GF
database:
  default:
    - link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
      role: "master"
    - link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
      role: "slave"
server:
  openapiPath: "/api.json"
  swaggerPath: "/api"

rabbitmq:
  server: amqp://test:test@localhost:5672/
  reconnect: 3 # Seconds When reconnecting to the server after connection failure
  reinit: 1 # Seconds When setting up the channel after a channel exception
  resend: 1 # Seconds When resending messages the server didn't confirm
redis:
  # Singleton 1
  default:
    address: 192.168.3.207:6379
    db: 1
    pass: lovelacelee
    idleTimeout: 600

  # Singleton 2
  cache:
    address: 192.168.3.207:6379
    db: 1
    pass: lovelacelee
    idleTimeout: 600
# sync with GF
logger:
  path: "logs/" # Log file path. The default value is null, indicating that the device is disabled and output to the terminal only.
  file: "{Y-m-d}.log" # Log file format. The default is"{Y-m-d}.log"
  prefix: "" # Log output prefix. The default is empty
  level: "all" # Log output Level
  ctxKeys: [] # Customize the Context variable name, and automatically print the Context variable to the log. The default is empty
  header: true # Whether to print log headers. The default true
  stdout: true # Whether logs are simultaneously output to the terminal. The default true
  rotateSize: 0 # Scrolling split files by log file size. The default value is 0, which indicates that the rolling shard feature is disabled
  rotateExpire: 0 # File scrolling is split based on log file intervals. The default value is 0, which indicates that the rolling shard feature is disabled
  rotateBackupLimit: 0 # Clears shard files based on the number of files shard. This is valid when the scrolling shard feature is enabled. The default value is 0, indicating that no backup is performed
  rotateBackupExpire: 0 # Cleans shard files according to the shard file validity period, valid when the rolling shard feature is enabled. The default value is 0, indicating that no backup is performed
  rotateBackupCompress: 0 # Compression ratio (0-9) of the scroll shard file. The default value is 0, indicating no compression
  rotateCheckInterval: "1h" # Generally, you do not need to set the time detection interval for rolling segmentation. The default value is 1 hour
  stdoutColorDisabled: false # Turn off terminal color printing. The default open
  writerColorEnable: false # Whether the log file is colored. The default value is false, which indicates no color
