name: Static Analysis
on: [push, pull_request]
permissions:
  contents: read

jobs:
  static_analysis:
    runs-on: ${{matrix.os}}
    strategy:
      matrix: 
        os: [ubuntu-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: '1.18'

    - name: Get dependencies
      run: |
        sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        go install honnef.co/go/tools/cmd/staticcheck@v0.3.0
    - name: Cleanup repository
      run: rm -rf vendor/

    - name: Vet
      run: go vet -tags ci ./...

    - name: Gocyclo
      run: gocyclo -over 50 .

    - name: Staticcheck
      run: staticcheck ./...
